services:
  backend:
    build: ./backend
    container_name: "docker-app"
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
    networks:
      - spring-mongodb
  mongo_db:
    image: mongo:latest
    container_name: "docker-mongodb"
    volumes:
      - dbdata:/data/db
    networks:
      - spring-mongodb
    expose:
      - 27017
  mongo-seed:
    build:
      context: ./mongo-seed
      dockerfile: Dockerfile
    depends_on:
      - mongo_db
    restart: on-failure
    networks:
      - spring-mongodb
volumes:
  dbdata:
networks:
  spring-mongodb:
      driver: bridge